# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/py_mobile_aat',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/py_mobile_aat',
                'lib_path': 'py_mobile_aat'},
  'syms': {'py_mobile_aat.core': {'py_mobile_aat.core.foo': ('core.html#foo', 'py_mobile_aat/core.py')}}}
